// Mocks generated by Mockito 5.4.6 from annotations
// in tote_bag/test/widgets/list_item_grid_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tote_bag/models/product.dart' as _i7;
import 'package:tote_bag/models/shopping_list.dart' as _i2;
import 'package:tote_bag/models/shopping_list_item.dart' as _i3;
import 'package:tote_bag/services/favorite_service.dart' as _i6;
import 'package:tote_bag/services/shopping_list_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeShoppingList_0 extends _i1.SmartFake implements _i2.ShoppingList {
  _FakeShoppingList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeShoppingListItem_1 extends _i1.SmartFake
    implements _i3.ShoppingListItem {
  _FakeShoppingListItem_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShoppingListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListService extends _i1.Mock
    implements _i4.ShoppingListService {
  MockShoppingListService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.ShoppingList>> getLists() => (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.ShoppingList>>.value(<_i2.ShoppingList>[]),
      ) as _i5.Future<List<_i2.ShoppingList>>);

  @override
  _i5.Future<_i2.ShoppingList> getListById(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [listId],
        ),
        returnValue: _i5.Future<_i2.ShoppingList>.value(_FakeShoppingList_0(
          this,
          Invocation.method(
            #getListById,
            [listId],
          ),
        )),
      ) as _i5.Future<_i2.ShoppingList>);

  @override
  _i5.Future<_i2.ShoppingList> createList({
    required String? name,
    String? description,
    String? color,
    String? icon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createList,
          [],
          {
            #name: name,
            #description: description,
            #color: color,
            #icon: icon,
          },
        ),
        returnValue: _i5.Future<_i2.ShoppingList>.value(_FakeShoppingList_0(
          this,
          Invocation.method(
            #createList,
            [],
            {
              #name: name,
              #description: description,
              #color: color,
              #icon: icon,
            },
          ),
        )),
      ) as _i5.Future<_i2.ShoppingList>);

  @override
  _i5.Future<_i2.ShoppingList> updateList({
    required String? listId,
    String? name,
    String? description,
    String? color,
    String? icon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [],
          {
            #listId: listId,
            #name: name,
            #description: description,
            #color: color,
            #icon: icon,
          },
        ),
        returnValue: _i5.Future<_i2.ShoppingList>.value(_FakeShoppingList_0(
          this,
          Invocation.method(
            #updateList,
            [],
            {
              #listId: listId,
              #name: name,
              #description: description,
              #color: color,
              #icon: icon,
            },
          ),
        )),
      ) as _i5.Future<_i2.ShoppingList>);

  @override
  _i5.Future<void> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ShoppingListItem> addItem({
    required String? listId,
    required String? name,
    int? quantity = 1,
    String? unit,
    String? notes,
    String? category,
    String? barcode,
    String? productId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [],
          {
            #listId: listId,
            #name: name,
            #quantity: quantity,
            #unit: unit,
            #notes: notes,
            #category: category,
            #barcode: barcode,
            #productId: productId,
          },
        ),
        returnValue:
            _i5.Future<_i3.ShoppingListItem>.value(_FakeShoppingListItem_1(
          this,
          Invocation.method(
            #addItem,
            [],
            {
              #listId: listId,
              #name: name,
              #quantity: quantity,
              #unit: unit,
              #notes: notes,
              #category: category,
              #barcode: barcode,
              #productId: productId,
            },
          ),
        )),
      ) as _i5.Future<_i3.ShoppingListItem>);

  @override
  _i5.Future<_i3.ShoppingListItem> updateItem({
    required String? listId,
    required String? itemId,
    String? name,
    int? quantity,
    String? unit,
    String? notes,
    bool? isChecked,
    String? category,
    int? order,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [],
          {
            #listId: listId,
            #itemId: itemId,
            #name: name,
            #quantity: quantity,
            #unit: unit,
            #notes: notes,
            #isChecked: isChecked,
            #category: category,
            #order: order,
          },
        ),
        returnValue:
            _i5.Future<_i3.ShoppingListItem>.value(_FakeShoppingListItem_1(
          this,
          Invocation.method(
            #updateItem,
            [],
            {
              #listId: listId,
              #itemId: itemId,
              #name: name,
              #quantity: quantity,
              #unit: unit,
              #notes: notes,
              #isChecked: isChecked,
              #category: category,
              #order: order,
            },
          ),
        )),
      ) as _i5.Future<_i3.ShoppingListItem>);

  @override
  _i5.Future<void> deleteItem({
    required String? listId,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [],
          {
            #listId: listId,
            #itemId: itemId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> shareList({
    required String? listId,
    required String? email,
    required String? permission,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareList,
          [],
          {
            #listId: listId,
            #email: email,
            #permission: permission,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [FavoriteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteService extends _i1.Mock implements _i6.FavoriteService {
  MockFavoriteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i7.Product>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Product>>.value(<_i7.Product>[]),
      ) as _i5.Future<List<_i7.Product>>);

  @override
  _i5.Future<void> addFavorite(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [productId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFavorite(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [productId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> toggleFavorite(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [productId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isFavorite(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [productId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
